// ===== SLY RIDES — Multi-Language Support (EN / ES) =====
(function () {
  "use strict";

  // ── Translation dictionaries ──────────────────────────────────────────────
  var TRANSLATIONS = {
    en: {
      nav: {
        browseCars:        "Browse Cars",
        howItWorks:        "How It Works",
        about:             "About",
        contact:           "Contact",
        reviews:           "Reviews",
        callNow:           "Call Now to Get Approved Today",
        home:              "Back to Homepage",
        backToHome:        "\u2190 Back to Homepage",
        homeLink:          "Home",
        videoTestimonial:  "Video Testimonial"
      },
      // index.html
      hero: {
        applyNow: "Apply Now"
      },
      stats: {
        yearsExp:      "Years Experience",
        happyCust:     "Happy Customers",
        satisfaction:  "Customer Satisfaction",
        safetyRating:  "Safety Rating"
      },
      hiw: {
        heading:    "How It Works",
        step1title: "1. Submit Your Application",
        step1body:  "Click Apply Now and fill out our quick rental application. Provide your name, phone number, age, driving experience, delivery app(s), and a copy of your driver\u2019s license for review.",
        step2title: "2. Get Approved",
        step2body:  "Our team reviews your application and contacts you to complete the approval process. You\u2019ll receive confirmation once you\u2019re approved and ready to book.",
        step3title: "3. Choose Your Car & Book Dates",
        step3body:  "Once approved, browse our available vehicles, pick the one that fits your needs, and select your pickup and return dates.",
        step4title: "4. Sign the Agreement",
        step4body:  "Review and e-sign your rental agreement online \u2014 no printing, no waiting, no back-and-forth.",
        step5title: "5. Pay & Drive",
        step5body:  "Complete your secure payment \u2014 then hit the road!",
        milesTitle: "Unlimited Mileage",
        milesBody:  "Drive as much as you need without worrying about mileage limits. Our rentals include unlimited mileage so you can focus on your trips, rideshare work, or daily driving with complete flexibility.",
        insTitle:   "Insurance Requirements",
        insBody:    "All of our vehicles are fully insured. However, renters are required to have their own insurance coverage to protect themselves in case of an accident. You may use your personal auto insurance if it meets the required coverage, or you can contact us to arrange insurance coverage when renting the vehicle."
      },
      testimonials: {
        heading:    "Hear It Straight From Our Customers",
        subheading: "Real drivers. Real stories. See why LA trusts SLY Rides."
      },
      about: {
        heading: "About SLY Transportation Services",
        body:    "SLY Transportation Services provides reliable, professional car rental solutions for Los Angeles visitors and rideshare drivers. Whether you\u2019re exploring the city or earning on platforms like Uber, Lyft, or DoorDash, our well-maintained fleet \u2014 from fuel-efficient sedans to head-turning rides \u2014 keeps you moving with confidence. We offer flexible rental terms, unlimited mileage, and responsive customer support, because your time and experience matter.",
        valuesTitle: "Our Values: Safety, Sustainability & Service Excellence",
        valuesBody:  "At SLY Transportation Services, our commitment is simple: safe, efficient, and professional transportation \u2014 every time. Every vehicle in our fleet is regularly inspected and meticulously cleaned. Every rental is backed by transparent pricing and a team that genuinely cares. Safe, reliable service isn\u2019t just a promise here \u2014 it\u2019s our standard."
      },
      applyModal: {
        title:       "Apply to Rent",
        subtitle:    "Fill out the form below to start your application. We\u2019ll review your information and contact you shortly.",
        labelName:   "Full Name",
        labelPhone:  "Phone Number",
        labelEmail:  "Email Address",
        labelLicense:"Driver\u2019s License",
        labelAge:    "Age",
        labelExp:    "Driving Experience",
        labelApps:   "Delivery App(s)",
        placeholderName:  "First and last name",
        placeholderPhone: "(213) 555-0100",
        placeholderEmail: "you@example.com",
        placeholderAge:   "Your age",
        expPlaceholder:   "-- Select your experience --",
        expLt3mo:   "Less than 3 months",
        exp3mo1yr:  "3 months \u2013 1 year",
        exp1to2:    "1\u20132 years",
        exp3to5:    "3\u20135 years",
        exp6to10:   "6\u201310 years",
        expGt10:    "More than 10 years",
        sendCode:    "Send Code",
        terms:       "I agree to the",
        smsConsent:  "I agree to receive SMS messaging related to my booking, including confirmation, reminders, and support updates. Message rates and data may apply.",
        backBtn:     "\u2190 Back to Home",
        submitBtn:   "Submit Application",
        uploadLicense: "\uD83D\uDCF7 Upload License (JPG, PNG, or PDF \u00B7 max 5\u00A0MB)",
        phoneVerified: "\u2713 Phone verified",
        codeSentNote: "Code sent to your phone \u2014 valid 10 min.",
        resendBtn:   "Resend",
        resendFmt:   "Resend ({secs}s)",
        sendingCode: "Sending\u2026",
        sentDone:    "Sent \u2713",
        licenseTypeError:   "Only JPG, PNG, or PDF files are accepted.",
        licenseSizeError:   "File must be under 5\u00a0MB.",
        invalidAge:         "Please enter a valid age.",
        selectApp:          "Please select at least one delivery app.",
        agreeTermsRequired: "You must agree to the Rental Terms & Conditions.",
        agreeSmsRequired:   "You must agree to receive SMS booking notifications.",
        uploadLicenseReq:   "Please upload a copy of your driver\u2019s license.",
        submitting:         "Submitting your application\u2026",
        enterPhoneFirst:    "Please enter your phone number first.",
        codeSentPhone:      "A 6-digit code was sent to your phone.",
        networkError:       "Network error. Please check your connection and try again.",
        otpSentError:       "Failed to send verification code. Please try again.",
        verifyPhoneFirst:   "Please verify your phone number before submitting.",
        generalError:       "Something went wrong. Please try again."
      },
      // cars.html
      fleet: {
        heading:    "Uber & Lyft Rental Cars in Los Angeles",
        subheading: "Reliable weekly rideshare rentals for Uber, Lyft, and delivery drivers. All vehicles are fully rideshare\u2011ready with unlimited miles.",
        sidebarTitle: "Browse by Type",
        filterAll:      "All Cars",
        filterEconomy:  "Economy / Ridesharing",
        filterSlingshot:"Slingshots",
        bookNow:     "Book Now",
        available:          "● Available",
        unavailable:        "● Unavailable",
        currentlyBooked:    "🔴 Currently Booked",
        nextAvailable:      "Next Available: {date}",
        booked:             "Booked",
        joinWaitlist:       "Join Waitlist",
        extendRental:       "⏱️ Extend Rental",
        availableToday:     "✓ Available Today",
        waitlistDeposit:    "Join Waitlist — $50 Deposit",
        waitlistHeading:    "🔔 Join the Waitlist",
        waitlistSubtitle:   "This vehicle is currently booked. Pay a $50 non-refundable <strong>waitlist deposit</strong> to lock your place in line — it goes toward your rental when the car becomes available.",
        waitlistNextLine:   "Next available: {date}",
        waitlistQueueNote:  "First come, first served. You'll get a payment link when the car is ready for your dates.",
        waitlistPrefPickup: "Preferred Pickup Date",
        waitlistPrefReturn: "Preferred Return Date",
        waitlistJoinBtn:    "🔔 Join Waitlist — Pay $50 Deposit",
        waitlistSuccess:    "⏳ Application Received!",
        waitlistSuccessBody: "Your waitlist application for the {car} is under review. We'll email you within 24–48 hours.",
        waitlistIdUpload:   "Driver's License / State ID",
        waitlistIdHint:     "Upload a clear photo or scan of your driver's license or state ID (required).",
        waitlistIdRequired: "Please upload your Driver's License or State ID to join the waitlist.",
        waitlistPayHint:    "Enter your name, email, preferred dates, and upload your driver's license to reserve your spot.",
        driverEarnings: "\uD83D\uDCB0 Driver Earnings Example (Los Angeles)",
        mostPopular: "Most Popular",
        bestValue:   "Best Value",
        rentalPlans: "Rental Plans",
        slingshotTagline: "Built for Thrills \u2022 Pure Fun",
        slingshotSub: "Experience the Ultimate City Ride",
        slingshotLi1: "\uD83C\uDF34 Cruise the streets of Los Angeles in style",
        slingshotLi2: "\u26A1 Feel the open-air rush of a 3-wheeled sports car",
        slingshotLi3: "\uD83C\uDFAF Perfect for exploring LA, photo shoots & special occasions",
        slingshotCta: "Limited availability \u2014 reserve yours today",
        sports2seater: "Sports \u2022 2-Seater",
        sedan5seater: "Sedan \u2022 5 Seater",
        rideshareReadyBadge: "\uD83D\uDE97 Uber & Lyft Ready",
        unlimitedMilesBadge: "\u221E Unlimited Miles",
        earningsLi1: "Avg. weekly Uber/Lyft earnings:",
        earningsLi2: "Weekly rental:",
        earningsLi3: "Est. driver take-home:",
        highDemand: "\uD83D\uDD25 High demand \u2014 reserve today",
        limitedAvail: "\u26A1 Limited vehicles available",
        reserveVehicle: "Reserve This Vehicle",
        driverReqHeading: "Driver Requirements",
        driverReq1: "\uD83E\uDE96 Valid Driver\u2019s License",
        driverReq2: "\uD83D\uDE97 Active or eligible Uber / Lyft driver account",
        driverReq3: "\uD83C\uDF82 Minimum age 21",
        whyHeading: "Why Drivers Choose SLY Transportation",
        why1: "\u2705 Rideshare\u2011approved vehicles",
        why2: "\u267E\uFE0F Unlimited miles for Uber, Lyft, and delivery",
        why3: "\uD83D\uDCB0 Affordable weekly rentals",
        why4: "\uD83D\uDD27 Reliable vehicles ready to drive",
        why5: "\uD83D\uDD11 Keep the same vehicle as long as payments stay current",
        ctaHeading: "Start Driving Today",
        ctaSub: "Reserve your rideshare vehicle and begin earning with Uber, Lyft, or delivery apps immediately.",
        ctaBtn: "Browse Available Vehicles \u2191",
        unitDay: "day",
        unitWeek: "week",
        unitBiweek: "2 weeks",
        unitMonth: "month",
        unitHrs: "hrs",
        priceFrom: "from",
        hours: "Hours",
        slingshotPrice: "$200 / 3hrs \u2022 $250 / 6hrs \u2022 $350 / 24hrs \u2022 deposit equal to rental fee"
      },
      // car.html (booking page)
      booking: {
        backToHome:    "\u2B05 Back to Home",
        pickupDate:    "Pickup Date",
        returnDate:    "Return Date",
        duration:      "Duration",
        days:          "days",
        selectTier:    "Select Duration",
        fullName:      "Full Name",
        email:         "Email",
        phone:         "Phone",
        uploadId:      "Driver\u2019s License / ID",
        uploadInsurance: "Insurance Card (Optional)",
        rentalAgreement: "Rental Agreement",
        iAgree:        "I have read and agree to the",
        agreementLink: "Rental Agreement",
        signature:     "Your Signature",
        signaturePh:   "Type your full name to sign",
        confirmSig:    "Confirm Signature",
        payNow:        "\uD83D\uDCB3 Pay Now",
        protection:    "Damage Protection Plan (DPP)",
        dppDesc:       "Covers accidental damage during your rental period.",
        total:         "Total",
        deposit:       "Deposit",
        orderSummary:  "Order Summary",
        completeReservation: "Complete Your Reservation",
        pickupTime: "Pickup Time",
        rentalDuration: "Rental Duration",
        returnTime: "Return Time",
        returnTimeSame: "(same as pickup time)",
        namePh: "Enter your full name",
        emailPh: "Enter your email",
        phonePh: "Enter your phone number",
        smsConsent: "By submitting this form, you agree to receive SMS messaging regarding vehicle availability. Reply STOP to opt out.",
        idNote: "A valid government-issued ID is required to confirm your rental.",
        fileNotSelected: "No file selected",
        accepted: "Accepted: JPG, PNG, PDF",
        insuranceQuestion: "\uD83D\uDEE1\uFE0F Do you have auto insurance that covers rental vehicles?",
        hasInsurance: "Yes, I have rental car coverage",
        noInsurance: "Add Damage Protection",
        uploadInsuranceLabel: "\uD83D\uDCCE Upload Proof of Insurance",
        insuranceNote: "Valid auto insurance documentation is required for all rentals.",
        dppWarning: "\u26A0\uFE0F Your Personal Auto Insurance may not cover rental vehicles",
        dppPrice: "Protect yourself with our <strong>Damage Protection Plan: Basic &mdash; $15/day &bull; Standard &mdash; $30/day &bull; Premium &mdash; $50/day</strong>",
        dppWhatsIncluded: "What\u2019s included:",
        dppItem1: "\u2705 Covers accidental vehicle damage",
        dppItem2: "\u2705 Reduces your liability (Basic: $2,500 \u2022 Standard: $1,000 \u2022 Premium: $500)",
        step1SignLabel: "\uD83D\uDCC4 Step 1: Read & Sign your Rental Agreement",
        signAgreementBtn: "\u270D Review & Sign Rental Agreement",
        signatureLabel: "Type your full legal name to sign:",
        signatureNote: "Typing your name above constitutes your legal electronic signature.",
        signatureCapacity: "By signing, you confirm that you are <strong>21 years of age or older</strong> and have full legal capacity to enter into this binding rental agreement.",
        confirmSign: "\u2705 I Agree & Sign",
        cancelSign: "Cancel",
        agreeLabel: "I have read and signed the Rental Agreement & Terms",
        refundNotice: "\u26A0\uFE0F <strong>No-Refund Policy:</strong> All payments are final once a booking is confirmed. Cancellations or no-shows after booking are not eligible for a refund. Please review your reservation details carefully before completing payment. Refunds may be issued only if the company cancels or cannot fulfill the rental.",
        subtotalLabel: "Subtotal:",
        salesTaxLabel: "Sales Tax:",
        taxNote: "(+ applicable sales tax)",
        payHint: "Fill in dates, enter your name, email, and phone number, upload your ID, select your insurance coverage option (and upload proof if you have coverage), and sign & agree to terms to enable payment.",
        cancelPayment: "\u2190 Change booking details",
        browseOther:   "Browse other available vehicles",
        earningsTagline: "Uber & Lyft Ready \u2022 Unlimited Miles",
        earningsTitle: "Driver Earnings Example (Los Angeles)",
        earningsRow1: "Average weekly earnings: $1,200 \u2013 $1,600",
        earningsRow2Html: "Weekly rental: <span class=\"earnings-yellow\">$350</span>",
        earningsRow3Html: "<span class=\"earnings-green\">Estimated take-home:</span> $850 \u2013 $1,250",
        earningsCtaHtml: "<span class=\"earnings-yellow\">Limited vehicles available</span> \u2014 reserve today",
        slingshotTagline: "\uD83C\uDFCE\uFE0F Built for Thrills \u2022 Pure Fun",
        payPrefix:            "Pay $",
        reserveWithDeposit:   "\uD83D\uDD12 Reserve with $50 Deposit",
        reservationDepositLabel: "Reservation deposit (non-refundable)",
        loadingPayment:       "Loading payment form\u2026",
        processingPayment:    "Processing\u2026",
        alertVehicleNotFound: "Vehicle not found.",
        alertIdType:          "Please upload a valid ID document (JPG, PNG, or PDF)",
        alertFileSize:        "File size must be less than 5MB",
        alertInsuranceType:   "Please upload a valid insurance document (JPG, PNG, or PDF)",
        alertEmail:           "Please enter your email address.",
        alertName:            "Please enter your full name.",
        alertPhone:           "Please enter your phone number.",
        loadError:            "Could not load the payment form. Please refresh the page and try again, or contact support.",
        signedBtn:            "\u2705 Rental Agreement Signed",
        signedByNote:         "Signed by {name}. Check the box below to confirm.",
        nameError:            "Please enter at least a first and last name.",
        sigError:             "Signature must match the full name entered in the booking form.",
        calcAtCheckout:       "Calculated at checkout",
        tierRentalFmt:        "{label} rental",
        securityDepositRef:   "Security deposit (refundable)",
        securityDeposit:      "Security deposit",
        salesTaxFmt:          "Sales tax ({rate}%)",
        salesTax:             "Sales tax",
        dppSlingshotFmt1:     "Damage Protection Plan (1 day \u00D7 ${price}/day)",
        dppSlingshotFmtN:     "Damage Protection Plan ({days} days \u00D7 ${price}/day)",
        dppFmt:               "Damage Protection Plan ({detail})",
        fmtMonth1:            "1 month \u00D7 ${price}/mo",
        fmtMonthN:            "{n} months \u00D7 ${price}/mo",
        fmtTwoWeeks1:         "1 2-week period \u00D7 ${price}",
        fmtTwoWeeksN:         "{n} 2-week periods \u00D7 ${price}",
        fmtWeek1:             "1 week \u00D7 ${price}/wk",
        fmtWeekN:             "{n} weeks \u00D7 ${price}/wk",
        fmtDay1:              "1 day \u00D7 ${price}/day",
        fmtDayN:              "{n} days \u00D7 ${price}/day"
      },
      agreement: {
        title: "SLY TRANSPORTATION SERVICES \u2014 CAR RENTAL AGREEMENT",
        depositHeading: "SECURITY DEPOSIT (Refundable)",
        partiesHeading: "PARTIES",
        partiesOwner: "<strong>Owner:</strong> SLY Transportation Services \u2014 (213) 916-6606 \u2014 info@slytrans.com",
        partiesRenter: "<strong>Renter:</strong> Name, address, phone, email, driver\u2019s license number, and date of birth as provided at time of booking.",
        vehicleHeading: "VEHICLE INFORMATION",
        vehicleMake: "Make",
        vehicleModel: "Model",
        vehicleYear: "Year",
        vehicleVin: "VIN / Plate",
        vehicleColor: "Color",
        fuelInspection: "Fuel Level at Pickup: Full &nbsp; Half &nbsp; Quarter &nbsp;&nbsp;&nbsp; Condition Photos Attached: Yes",
        rentalPeriodHeading: "RENTAL PERIOD",
        rentalPeriodBody: "Rental start and end dates/times are as specified at the time of booking. The vehicle must be returned to the same location at the agreed return date and time.",
        lateFeeBody: "<strong>Late Fee:</strong> $50/day after a 2-hour grace period.",
        slingshotLateFeeBody: "<strong>Late Fee:</strong> $100/hour after a 30-minute grace period.",
        mileageFuelHeading: "MILEAGE, GEOGRAPHIC USE &amp; VEHICLE TRACKING POLICY",
        mileageLimitBody: "Mileage is unlimited within a designated local area only. All vehicle use must remain within <strong>Los Angeles County</strong> or within a <strong>50-mile radius of Los Angeles</strong>, unless otherwise approved in writing by the host.",
        geoAuthBody: "Travel outside the permitted area is not allowed without prior written authorization. This includes, but is not limited to, trips to San Diego, San Francisco, Las Vegas, or any out-of-state destinations. Requests for extended travel must be submitted in advance and are subject to approval at the host's sole discretion.",
        geoPenaltyBody: "Any unauthorized use of the vehicle outside the approved geographic area will result in a <strong>$500 penalty fee</strong> and may lead to early termination of the rental without refund, in accordance with platform policies.",
        gpsTrackingBody: "The vehicle is equipped with a <strong>GPS tracking system</strong> for security, safety, and compliance purposes. By renting this vehicle, you acknowledge and consent to location monitoring during the rental period.",
        fuelHeading: "FUEL POLICY",
        fuelPolicyBody: "The vehicle must be returned with the same fuel level as at the start of the trip. Any deficiency will be charged at a rate of <strong>$5 per gallon</strong>.",
        insuranceHeading: "INSURANCE &amp; LIABILITY",
        insuranceMustProvide: "Renter must provide <strong>one of the following</strong> prior to vehicle release:",
        insuranceLi1: "Valid personal auto insurance covering rental vehicles (proof required), <strong>OR</strong>",
        insuranceLi2: "Purchase of SLY Transportation Services Damage Protection Plan",
        dppOptionalBody: "<strong>Damage Protection Plan (Optional):</strong> Basic &mdash; $15/day &bull; Standard &mdash; $30/day &bull; Premium &mdash; $50/day",
        dppReduces: "This plan reduces the renter\u2019s financial responsibility for covered vehicle damage. Liability cap depends on plan selected: Basic \u2014 $2,500 \u2022 Standard \u2014 $1,000 \u2022 Premium \u2014 $500 per incident.",
        withoutPlanBody: "<strong>Without Protection Plan:</strong> Renter is fully responsible for all damages and associated costs, including but not limited to:",
        withoutLi1: "Full cost of vehicle repair or replacement",
        withoutLi2: "Loss of use (rental downtime)",
        withoutLi3: "Diminished value",
        withoutLi4: "Administrative, towing, and storage fees",
        withPlanBody: "<strong>With Protection Plan:</strong> Renter\u2019s maximum liability for covered vehicle damage is limited per plan (Basic: $2,500 \u2022 Standard: $1,000 \u2022 Premium: $500 per incident). Any damage costs exceeding the cap are covered by the plan, provided all terms of this agreement are followed.",
        exclusionsBody: "<strong>Exclusions (Protection Plan Void If):</strong>",
        exclusionLi1: "Driver is under the influence of drugs or alcohol",
        exclusionLi2: "Unauthorized driver operates the vehicle",
        exclusionLi3: "Reckless, illegal, or negligent use",
        exclusionLi4: "Off-road or prohibited use",
        exclusionLi5: "Failure to report damage within 24 hours",
        exclusionLi6: "Violation of rental agreement terms",
        thirdPartyBody: "<strong>Third-Party Liability:</strong> Renter is solely responsible for any third-party claims, including bodily injury, property damage, or death. SLY Transportation Services is not liable for renter negligence. Renter agrees to indemnify and hold harmless SLY Transportation Services from any claims, losses, or expenses arising from vehicle use.",
        useRestrictionsHeading: "USE RESTRICTIONS",
        useRestrictionsIntro: "Renter agrees to all of the following restrictions:",
        useRestrictionsRow1: "No smoking &nbsp; No pets &nbsp; No off-road use &nbsp; No subleasing",
        useRestrictionsRow2: "Approved drivers only &nbsp; No racing or towing &nbsp; No commercial hauling",
        slingshotSpeedHeading: "SLINGSHOT SPEED POLICY",
        slingshotSpeedBody: "<strong>Speed Limit:</strong> The posted speed limit is 65 mph. Renters may not exceed <strong>75 mph</strong> under any circumstances. Exceeding 75 mph at any time constitutes a violation of this agreement.",
        slingshotStrikePolicy: "<strong>Strike Policy:</strong> After two (2) speed or agreement violations (\"strikes\"), the renter's security deposit becomes <strong>non-refundable</strong>.",
        conditionHeading: "CONDITION INSPECTION",
        conditionBody: "Vehicle is inspected and accepted as-is at time of pickup. Condition photos are taken at pickup. Renter must report any pre-existing damage within 24 hours of pickup.",
        terminationHeading: "TERMINATION",
        terminationBody: "SLY Transportation Services may terminate this agreement immediately for breach of terms, unpaid fees, unlawful use, or safety violations. Renter is liable for all costs to recover the vehicle.",
        paymentTermsHeading: "PAYMENT TERMS",
        paymentTermsBody: "All fees are due at pickup. Late payments accrue interest at 1.5% per month. NSF (returned check) fee: $35.",
        noRefundBody: "\u26A0 <strong>No-Refund Policy:</strong> All payments are final once a booking is confirmed. Cancellations or no-shows after booking are not eligible for a refund. Refunds may be issued only if SLY Transportation cancels or cannot fulfill the rental.",
        chargebackHeading: "PAYMENT AUTHORIZATION &amp; CHARGEBACK POLICY",
        chargebackIntro: "By signing this agreement, renter expressly authorizes SLY Transportation Services to charge the payment method on file for all amounts owed under this agreement, including but not limited to:",
        chargebackLi1: "Rental charges and extensions",
        chargebackLi2: "Security deposit and any applicable deductions",
        chargebackLi3: "Vehicle damage, repair, or replacement costs",
        chargebackLi4: "Loss of use and diminished value",
        chargebackLi5: "Fuel, cleaning, smoking, or excess wear fees",
        chargebackLi6: "Towing, storage, tickets, tolls, and administrative fees",
        chargebackAfter: "Renter agrees that these charges may be processed after the rental period if additional costs are identified upon inspection or later discovery.",
        chargebackAcknowledge: "Renter acknowledges that all charges are valid, agreed upon, and authorized under this contract. Renter agrees not to dispute, reverse, or initiate a chargeback for any legitimate charge incurred in accordance with this agreement.",
        chargebackDisputeBody: "<strong>In the event of a payment dispute or chargeback, renter agrees that:</strong>",
        chargebackDisputeLi1: "This signed agreement serves as binding proof of authorization",
        chargebackDisputeLi2: "SLY Transportation Services may submit this agreement, along with rental records, photos, inspection reports, and communication logs, as evidence to the payment processor",
        chargebackDisputeLi3: "Renter remains financially responsible for all charges, including any fees resulting from the dispute",
        chargebackChargeback: "If a chargeback is initiated without valid cause, SLY Transportation Services reserves the right to pursue collection, legal action, and recovery of all associated costs, including reasonable attorney\u2019s fees where permitted by law.",
        governingLawHeading: "GOVERNING LAW",
        governingLawBody: "This agreement is governed by the laws of the State of California. Disputes shall be resolved in the courts of Los Angeles County. By signing, the renter acknowledges they have read, understood, and agreed to all terms above."
      },
      // contact.html
      contact: {
        heading:  "Contact Us",
        subtitle: "Have a question or need help? Send us a message and we\u2019ll get back to you promptly.",
        labelName:    "Your Name",
        labelEmail:   "Your Email",
        labelPhone:   "Phone (optional)",
        labelMessage: "Your Message",
        placeholderName:    "First and last name",
        placeholderEmail:   "you@example.com",
        placeholderPhone:   "(213) 555-0100",
        placeholderMessage: "How can we help you?",
        sendBtn:  "Send Message",
        otpLabel: "Verification Code",
        otpPh:    "Enter 6-digit code",
        sendOtp:  "Send Code",
        resend:   "Resend",
        emailVerified: "\u2713 Email verified",
        otpHint:      "Check your inbox for a 6-digit code (valid 10 min).",
        otpSent:      "Verification code sent! Check your inbox.",
        otpSentError: "Failed to send verification email. Please try again.",
        networkError: "Network error. Please check your connection and try again.",
        sendCodeBtn:  "Send Code",
        sentDone:     "Sent \u2713",
        sendingCode:  "Sending\u2026",
        resendFmt:    "Resend ({secs}s)",
        enterEmailFirst:   "Please enter your email address first.",
        enterValidEmail:   "Please enter a valid email address.",
        fillAllFields:     "Please fill in all required fields.",
        verifyEmailFirst:  "Please verify your email address before submitting.",
        enterOtpCode:      "Please enter the verification code sent to your email.",
        sending:           "Sending\u2026",
        generalError:      "Something went wrong. Please try again or call us at (213) 916-6606.",
        networkErrorFull:  "Network error. Please check your connection or call us at (213) 916-6606."
      },
      // success.html
      success: {
        title:      "\u2705 Payment Successful!",
        body:       "Thank you for booking with Sly Transportation Services LLC! Your car is reserved. We will be in touch shortly to confirm your rental details.",
        sending:    "Sending confirmation\u2026",
        homeBtn:    "Return to Checkout",
        failTitle:  "\u274C Payment Failed",
        failBody:   "Your payment was not completed. No charge was made. Please try booking again or contact us if you need help.",
        pendingTitle: "\u23F3 Payment Processing",
        pendingBody:  "Your payment is being processed. We will email you once it is confirmed. Please do not re-submit.",
        emailError: "We couldn\u2019t send your confirmation email automatically. Please contact us at slyservices@supports-info.com to confirm your booking.",
        tryAgain:  "Try Booking Again",
        verifying: "Verifying payment\u2026"
      },
      // cancel.html
      cancel: {
        title:   "\u274C Payment Canceled",
        body:    "Your payment was not completed. No charge was made. You can try again anytime!",
        homeBtn: "Back to Homepage",
        tryAgain: "Try Booking Again"
      },
      // thank-you.html
      thankyou: {
        title:          "\uD83C\uDF89 Thank You!",
        sub:            "Your submission has been received!",
        detail:         "Our team at Sly Transportation Services LLC will review your information and reach out to you shortly to complete your approval.",
        download:       "📄 Download PDF",
        fillAgain:      "🔄 Fill Again",
        questions:      "Questions? Call us:",
        browseCars:     "\uD83D\uDE97 Browse & Book a Car",
        backHome:       "\uD83C\uDFE0 Back to Home",
        approvedTitle:  "\uD83C\uDF89 You\u2019re Approved!",
        approvedSub:    "Congratulations \u2014 your application has been accepted!",
        approvedDetail: "You are now cleared to browse and book a vehicle with <strong>Sly Transportation Services LLC</strong>. Check your email for your official approval confirmation and next steps.",
        reviewTitle:    "\u23F3 Application Received!",
        reviewSub:      "We\u2019re reviewing your information now.",
        reviewDetail:   "Our team at <strong>Sly Transportation Services LLC</strong> will review your application and contact you within <strong>24 hours</strong>. Check your email and phone for updates.",
        declinedTitle:  "Application Update",
        declinedSub:    "We were unable to approve your application at this time.",
        declinedDetail: "Your application does not currently meet our rental requirements. A confirmation has been sent to your email. If you believe this is an error or have questions, please call us at <strong>(213) 916-6606</strong>."
      },
      // chatbot UI
      chatbot: {
        headerTitle:  "\uD83D\uDE97 Sly Transportation Services LLC Assistant",
        placeholder:  "Ask a question\u2026",
        sendBtn:      "Send",
        closeBtn:     "\u2715",
        welcome:      "Hi! \uD83D\uDC4B Looking to rent a car for DoorDash, Uber Eats, or other delivery apps?\n\nOur cars are <strong>$350/week with unlimited miles</strong>. I can help you get approved quickly.\n\nAsk me anything \u2014 pricing, requirements, earnings \u2014 or click below to apply!\n\n<a href=\"index.html\" id=\"chatApplyLink\">\uD83D\uDC49 Apply and get approved now</a>",
        fallback:     "I\u2019m not sure about that one \uD83E\uDD14\n\nTry asking about:\n\u2022 Pricing\n\u2022 Available cars\n\u2022 How to book\n\u2022 Delivery apps\n\u2022 Contact info\n\nOr email us at slyservices@supports-info.com"
      },
      footer: {
        copy: "\u00A9 2026 Sly Transportation Services LLC. All rights reserved.",
        privacyPolicy: "Privacy Policy"
      }
    },

    es: {
      nav: {
        browseCars:        "Ver Autos",
        howItWorks:        "C\u00F3mo Funciona",
        about:             "Nosotros",
        contact:           "Contacto",
        reviews:           "Rese\u00F1as",
        callNow:           "Llama Ahora para Obtener Aprobaci\u00F3n Hoy",
        home:              "Volver al Inicio",
        backToHome:        "\u2190 Volver al Inicio",
        homeLink:          "Inicio",
        videoTestimonial:  "Video Testimonial"
      },
      hero: {
        applyNow: "Solicitar Ahora"
      },
      stats: {
        yearsExp:     "A\u00F1os de Experiencia",
        happyCust:    "Clientes Satisfechos",
        satisfaction: "Satisfacci\u00F3n del Cliente",
        safetyRating: "Calificaci\u00F3n de Seguridad"
      },
      hiw: {
        heading:    "C\u00F3mo Funciona",
        step1title: "1. Env\u00EDa Tu Solicitud",
        step1body:  "Haz clic en Solicitar Ahora y completa nuestra breve solicitud de alquiler. Proporciona tu nombre, n\u00FAmero de tel\u00E9fono, edad, experiencia al volante, aplicaci\u00F3n(es) de entrega y una copia de tu licencia de conducir para revisi\u00F3n.",
        step2title: "2. Obt\u00E9n Aprobaci\u00F3n",
        step2body:  "Nuestro equipo revisa tu solicitud y se pone en contacto contigo para completar el proceso de aprobaci\u00F3n. Recibir\u00E1s confirmaci\u00F3n una vez aprobado y listo para reservar.",
        step3title: "3. Elige Tu Auto y Fechas",
        step3body:  "Una vez aprobado, navega por nuestros veh\u00EDculos disponibles, elige el que mejor se adapte a tus necesidades y selecciona tus fechas de recogida y devoluci\u00F3n.",
        step4title: "4. Firma el Contrato",
        step4body:  "Revisa y firma electr\u00F3nicamente tu contrato de alquiler en l\u00EDnea \u2014 sin imprimir, sin esperar, sin complicaciones.",
        step5title: "5. Paga y Maneja",
        step5body:  "\u00A1Completa tu pago seguro y sal a la carretera!",
        milesTitle: "Millaje Ilimitado",
        milesBody:  "Maneja todo lo que necesites sin preocuparte por l\u00EDmites de millaje. Nuestros alquileres incluyen millaje ilimitado para que puedas concentrarte en tus viajes, trabajo de viaje compartido o manejo diario con total flexibilidad.",
        insTitle:   "Requisitos de Seguro",
        insBody:    "Todos nuestros veh\u00EDculos est\u00E1n completamente asegurados. Sin embargo, los arrendatarios deben tener su propia cobertura de seguro para protegerse en caso de accidente. Puedes usar tu seguro de auto personal si cumple con la cobertura requerida, o contactarnos para organizar una cobertura cuando alquiles el veh\u00EDculo."
      },
      testimonials: {
        heading:    "Escucha Directamente de Nuestros Clientes",
        subheading: "Conductores reales. Historias reales. Descubre por qu\u00E9 LA conf\u00EDa en SLY Rides."
      },
      about: {
        heading: "Sobre SLY Transportation Services",
        body:    "SLY Transportation Services ofrece soluciones confiables y profesionales de alquiler de autos para visitantes de Los \u00C1ngeles y conductores de viaje compartido. Ya sea que explores la ciudad o generes ingresos en plataformas como Uber, Lyft o DoorDash, nuestra flota bien mantenida \u2014 desde sedanes eficientes hasta autos llamativos \u2014 te mantiene en movimiento con confianza. Ofrecemos t\u00E9rminos de alquiler flexibles, millaje ilimitado y soporte al cliente receptivo, porque tu tiempo y experiencia importan.",
        valuesTitle: "Nuestros Valores: Seguridad, Sostenibilidad y Excelencia en el Servicio",
        valuesBody:  "En SLY Transportation Services, nuestro compromiso es simple: transporte seguro, eficiente y profesional \u2014 siempre. Cada veh\u00EDculo de nuestra flota es inspeccionado y limpiado meticulosamente de manera regular. Cada alquiler est\u00E1 respaldado por precios transparentes y un equipo que genuinamente se preocupa. El servicio seguro y confiable no es solo una promesa aqu\u00ED \u2014 es nuestro est\u00E1ndar."
      },
      applyModal: {
        title:       "Solicitar Alquiler",
        subtitle:    "Completa el formulario a continuaci\u00F3n para iniciar tu solicitud. Revisaremos tu informaci\u00F3n y nos comunicaremos contigo pronto.",
        labelName:   "Nombre Completo",
        labelPhone:  "N\u00FAmero de Tel\u00E9fono",
        labelEmail:  "Correo Electr\u00F3nico",
        labelLicense:"Licencia de Conducir",
        labelAge:    "Edad",
        labelExp:    "Experiencia al Volante",
        labelApps:   "Aplicaci\u00F3n(es) de Entrega",
        placeholderName:  "Nombre y apellido",
        placeholderPhone: "(213) 555-0100",
        placeholderEmail: "tu@ejemplo.com",
        placeholderAge:   "Tu edad",
        expPlaceholder:   "-- Selecciona tu experiencia --",
        expLt3mo:   "Menos de 3 meses",
        exp3mo1yr:  "3 meses \u2013 1 a\u00F1o",
        exp1to2:    "1\u20132 a\u00F1os",
        exp3to5:    "3\u20135 a\u00F1os",
        exp6to10:   "6\u201310 a\u00F1os",
        expGt10:    "M\u00E1s de 10 a\u00F1os",
        sendCode:    "Enviar C\u00F3digo",
        terms:       "Acepto los",
        smsConsent:  "Acepto recibir mensajes SMS relacionados con mi reserva, incluyendo confirmaci\u00F3n, recordatorios y actualizaciones de soporte. Pueden aplicarse tarifas de mensajes y datos.",
        backBtn:     "\u2190 Volver al Inicio",
        submitBtn:   "Enviar Solicitud",
        uploadLicense: "\uD83D\uDCF7 Subir Licencia (JPG, PNG o PDF \u00B7 m\u00E1x 5\u00A0MB)",
        phoneVerified: "\u2713 Tel\u00E9fono verificado",
        codeSentNote: "C\u00F3digo enviado a tu tel\u00E9fono \u2014 v\u00E1lido 10 min.",
        resendBtn:   "Reenviar",
        resendFmt:   "Reenviar ({secs}s)",
        sendingCode: "Enviando\u2026",
        sentDone:    "Enviado \u2713",
        licenseTypeError:   "Solo se aceptan archivos JPG, PNG o PDF.",
        licenseSizeError:   "El archivo debe ser menor de 5\u00a0MB.",
        invalidAge:         "Por favor ingresa una edad v\u00E1lida.",
        selectApp:          "Por favor selecciona al menos una aplicaci\u00F3n de entrega.",
        agreeTermsRequired: "Debes aceptar los T\u00E9rminos y Condiciones del Alquiler.",
        agreeSmsRequired:   "Debes aceptar recibir notificaciones SMS de reservas.",
        uploadLicenseReq:   "Por favor sube una copia de tu licencia de conducir.",
        submitting:         "Enviando tu solicitud\u2026",
        enterPhoneFirst:    "Por favor ingresa tu n\u00FAmero de tel\u00E9fono primero.",
        codeSentPhone:      "Se envi\u00F3 un c\u00F3digo de 6 d\u00EDgitos a tu tel\u00E9fono.",
        networkError:       "Error de red. Por favor verifica tu conexi\u00F3n e int\u00E9ntalo de nuevo.",
        otpSentError:       "No se pudo enviar el c\u00F3digo de verificaci\u00F3n. Por favor int\u00E9ntalo de nuevo.",
        verifyPhoneFirst:   "Por favor verifica tu n\u00FAmero de tel\u00E9fono antes de enviar.",
        generalError:       "Algo sali\u00F3 mal. Por favor int\u00E9ntalo de nuevo."
      },
      fleet: {
        heading:    "Autos de Alquiler para Uber y Lyft en Los \u00C1ngeles",
        subheading: "Alquileres semanales confiables para conductores de Uber, Lyft y entrega. Todos los veh\u00EDculos est\u00E1n listos para viaje compartido con millaje ilimitado.",
        sidebarTitle: "Buscar por Tipo",
        filterAll:      "Todos los Autos",
        filterEconomy:  "Econ\u00F3mico / Viaje Compartido",
        filterSlingshot:"Slingshots",
        bookNow:     "Reservar Ahora",
        available:          "● Disponible",
        unavailable:        "● No Disponible",
        currentlyBooked:    "🔴 Actualmente Reservado",
        nextAvailable:      "Próximo disponible: {date}",
        booked:             "Reservado",
        joinWaitlist:       "Unirse a la Lista de Espera",
        extendRental:       "⏱️ Extender Alquiler",
        availableToday:     "✓ Disponible Hoy",
        waitlistDeposit:    "Unirse a la Lista de Espera — $50",
        waitlistHeading:    "🔔 Únete a la Lista de Espera",
        waitlistSubtitle:   "Este vehículo está actualmente reservado. Paga un <strong>depósito de lista de espera</strong> no reembolsable de $50 para asegurar tu lugar — se aplica al alquiler cuando el auto esté disponible.",
        waitlistNextLine:   "Próximo disponible: {date}",
        waitlistQueueNote:  "Por orden de llegada. Recibirás un enlace de pago cuando el auto esté listo para tus fechas.",
        waitlistPrefPickup: "Fecha de Recogida Preferida",
        waitlistPrefReturn: "Fecha de Devolución Preferida",
        waitlistJoinBtn:    "🔔 Unirse a la Lista — Pagar $50",
        waitlistSuccess:    "⏳ ¡Solicitud Recibida!",
        waitlistSuccessBody: "Tu solicitud para la lista de espera del {car} está bajo revisión. Te enviaremos un correo en 24–48 horas.",
        waitlistIdUpload:   "Licencia de Conducir / ID Estatal",
        waitlistIdHint:     "Sube una foto clara o escaneo de tu licencia de conducir o ID estatal (obligatorio).",
        waitlistIdRequired: "Por favor sube tu Licencia de Conducir o ID Estatal para unirte a la lista de espera.",
        waitlistPayHint:    "Ingresa tu nombre, correo, fechas preferidas y sube tu licencia de conducir para reservar tu lugar.",
        driverEarnings: "\uD83D\uDCB0 Ejemplo de Ganancias del Conductor (Los \u00C1ngeles)",
        mostPopular: "M\u00E1s Popular",
        bestValue:   "Mejor Valor",
        rentalPlans: "Planes de Alquiler",
        slingshotTagline: "Dise\u00F1ado para Emociones \u2022 Pura Diversi\u00F3n",
        slingshotSub: "Vive la M\u00E1xima Experiencia en la Ciudad",
        slingshotLi1: "\uD83C\uDF34 Recorre las calles de Los \u00C1ngeles con estilo",
        slingshotLi2: "\u26A1 Siente la adrenalina de un auto deportivo de 3 ruedas al aire libre",
        slingshotLi3: "\uD83C\uDFAF Perfecto para explorar LA, sesiones de fotos y ocasiones especiales",
        slingshotCta: "Disponibilidad limitada \u2014 reserva el tuyo hoy",
        sports2seater: "Deportivo \u2022 2 Plazas",
        sedan5seater: "Sed\u00E1n \u2022 5 Plazas",
        rideshareReadyBadge: "\uD83D\uDE97 Listo para Uber y Lyft",
        unlimitedMilesBadge: "\u221E Millaje Ilimitado",
        earningsLi1: "Ganancias semanales prom. Uber/Lyft:",
        earningsLi2: "Alquiler semanal:",
        earningsLi3: "Ingreso estimado del conductor:",
        highDemand: "\uD83D\uDD25 Alta demanda \u2014 reserva hoy",
        limitedAvail: "\u26A1 Veh\u00EDculos limitados disponibles",
        reserveVehicle: "Reservar Este Veh\u00EDculo",
        driverReqHeading: "Requisitos del Conductor",
        driverReq1: "\uD83E\uDE96 Licencia de Conducir V\u00E1lida",
        driverReq2: "\uD83D\uDE97 Cuenta activa o elegible de Uber / Lyft",
        driverReq3: "\uD83C\uDF82 Edad m\u00EDnima 21 a\u00F1os",
        whyHeading: "Por Qu\u00E9 los Conductores Eligen SLY Transportation",
        why1: "\u2705 Veh\u00EDculos aprobados para viaje compartido",
        why2: "\u267E\uFE0F Millaje ilimitado para Uber, Lyft y entrega",
        why3: "\uD83D\uDCB0 Alquileres semanales asequibles",
        why4: "\uD83D\uDD27 Veh\u00EDculos confiables listos para manejar",
        why5: "\uD83D\uDD11 Mant\u00E9n el mismo veh\u00EDculo mientras los pagos est\u00E9n al d\u00EDa",
        ctaHeading: "Comienza a Manejar Hoy",
        ctaSub: "Reserva tu veh\u00EDculo de viaje compartido y comienza a ganar con Uber, Lyft o aplicaciones de entrega de inmediato.",
        ctaBtn: "Ver Veh\u00EDculos Disponibles \u2191",
        unitDay: "d\u00EDa",
        unitWeek: "semana",
        unitBiweek: "2 semanas",
        unitMonth: "mes",
        unitHrs: "hrs",
        priceFrom: "desde",
        hours: "Horas",
        slingshotPrice: "$200 / 3hrs \u2022 $250 / 6hrs \u2022 $350 / 24hrs \u2022 dep\u00F3sito igual al costo de renta"
      },
      booking: {
        backToHome:    "\u2B05 Volver al Inicio",
        pickupDate:    "Fecha de Recogida",
        returnDate:    "Fecha de Devoluci\u00F3n",
        duration:      "Duraci\u00F3n",
        days:          "d\u00EDas",
        selectTier:    "Seleccionar Duraci\u00F3n",
        fullName:      "Nombre Completo",
        email:         "Correo Electr\u00F3nico",
        phone:         "Tel\u00E9fono",
        uploadId:      "Licencia de Conducir / ID",
        uploadInsurance: "Tarjeta de Seguro (Opcional)",
        rentalAgreement: "Contrato de Alquiler",
        iAgree:        "He le\u00EDdo y acepto el",
        agreementLink: "Contrato de Alquiler",
        signature:     "Tu Firma",
        signaturePh:   "Escribe tu nombre completo para firmar",
        confirmSig:    "Confirmar Firma",
        payNow:        "\uD83D\uDCB3 Pagar Ahora",
        protection:    "Plan de Protecci\u00F3n por Da\u00F1os (DPP)",
        dppDesc:       "Cubre da\u00F1os accidentales durante tu per\u00EDodo de alquiler.",
        total:         "Total",
        deposit:       "Dep\u00F3sito",
        orderSummary:  "Resumen del Pedido",
        completeReservation: "Completa Tu Reserva",
        pickupTime: "Hora de Recogida",
        rentalDuration: "Duraci\u00F3n del Alquiler",
        returnTime: "Hora de Devoluci\u00F3n",
        returnTimeSame: "(igual que la hora de recogida)",
        namePh: "Ingresa tu nombre completo",
        emailPh: "Ingresa tu correo electr\u00F3nico",
        phonePh: "Ingresa tu n\u00FAmero de tel\u00E9fono",
        smsConsent: "Al enviar este formulario, aceptas recibir mensajes SMS sobre disponibilidad de veh\u00EDculos. Responde STOP para cancelar.",
        idNote: "Se requiere una identificaci\u00F3n oficial v\u00E1lida para confirmar tu reserva.",
        fileNotSelected: "Ning\u00FAn archivo seleccionado",
        accepted: "Aceptados: JPG, PNG, PDF",
        insuranceQuestion: "\uD83D\uDEE1\uFE0F \u00BFTienes seguro de auto que cubra veh\u00EDculos de alquiler?",
        hasInsurance: "S\u00ED, tengo cobertura para autos de alquiler",
        noInsurance: "Agregar Protecci\u00F3n de Da\u00F1os",
        uploadInsuranceLabel: "\uD83D\uDCCE Subir Comprobante de Seguro",
        insuranceNote: "Se requiere documentaci\u00F3n de seguro de auto v\u00E1lida para todos los alquileres.",
        dppWarning: "\u26A0\uFE0F Tu seguro de auto personal puede no cubrir veh\u00EDculos de alquiler",
        dppPrice: "Prot\u00E9gete con nuestro <strong>Plan de Protecci\u00F3n de Da\u00F1os: B\u00E1sico &mdash; $15/d\u00EDa &bull; Est\u00E1ndar &mdash; $30/d\u00EDa &bull; Premium &mdash; $50/d\u00EDa</strong>",
        dppWhatsIncluded: "Qu\u00E9 incluye:",
        dppItem1: "\u2705 Cubre da\u00F1os accidentales al veh\u00EDculo",
        dppItem2: "\u2705 Reduce tu responsabilidad (B\u00E1sico: $2,500 \u2022 Est\u00E1ndar: $1,000 \u2022 Premium: $500)",
        step1SignLabel: "\uD83D\uDCC4 Paso 1: Lee y Firma tu Contrato de Alquiler",
        signAgreementBtn: "\u270D Revisar y Firmar Contrato de Alquiler",
        signatureLabel: "Escribe tu nombre legal completo para firmar:",
        signatureNote: "Escribir tu nombre arriba constituye tu firma electr\u00F3nica legal.",
        signatureCapacity: "Al firmar, confirmas que tienes <strong>21 a\u00F1os de edad o m\u00E1s</strong> y la capacidad legal plena para celebrar este contrato de alquiler vinculante.",
        confirmSign: "\u2705 Acepto y Firmo",
        cancelSign: "Cancelar",
        agreeLabel: "He le\u00EDdo y firmado el Contrato de Alquiler y los T\u00E9rminos",
        refundNotice: "\u26A0\uFE0F <strong>Pol\u00EDtica de No Reembolso:</strong> Todos los pagos son finales una vez confirmada la reserva. Las cancelaciones o ausencias despu\u00E9s de la reserva no son elegibles para reembolso. Revisa los detalles de tu reserva cuidadosamente antes de completar el pago. Los reembolsos solo se emiten si la empresa cancela o no puede cumplir con el alquiler.",
        subtotalLabel: "Subtotal:",
        salesTaxLabel: "Impuesto sobre Ventas:",
        taxNote: "(+ impuesto sobre ventas aplicable)",
        payHint: "Completa las fechas, ingresa tu nombre, correo y n\u00FAmero de tel\u00E9fono, sube tu identificaci\u00F3n, selecciona tu opci\u00F3n de seguro (y sube el comprobante si tienes cobertura), y firma y acepta los t\u00E9rminos para activar el pago.",
        cancelPayment: "\u2190 Cambiar detalles de reserva",
        browseOther:   "Ver otros veh\u00EDculos disponibles",
        earningsTagline: "Listo para Uber y Lyft \u2022 Millaje Ilimitado",
        earningsTitle: "Ejemplo de Ganancias del Conductor (Los \u00C1ngeles)",
        earningsRow1: "Ganancias semanales promedio: $1,200 \u2013 $1,600",
        earningsRow2Html: "Alquiler semanal: <span class=\"earnings-yellow\">$350</span>",
        earningsRow3Html: "<span class=\"earnings-green\">Ingreso estimado:</span> $850 \u2013 $1,250",
        earningsCtaHtml: "<span class=\"earnings-yellow\">Veh\u00EDculos limitados disponibles</span> \u2014 reserva hoy",
        slingshotTagline: "\uD83C\uDFCE\uFE0F Dise\u00F1ado para Emociones \u2022 Pura Diversi\u00F3n",
        payPrefix:            "Pagar $",
        reserveWithDeposit:   "\uD83D\uDD12 Reservar con $50 de Dep\u00F3sito",
        reservationDepositLabel: "Dep\u00F3sito de reserva (no reembolsable)",
        loadingPayment:       "Cargando formulario de pago\u2026",
        processingPayment:    "Procesando\u2026",
        alertVehicleNotFound: "Veh\u00EDculo no encontrado.",
        alertIdType:          "Por favor sube un documento de identidad v\u00E1lido (JPG, PNG o PDF)",
        alertFileSize:        "El archivo debe ser menor de 5MB",
        alertInsuranceType:   "Por favor sube un documento de seguro v\u00E1lido (JPG, PNG o PDF)",
        alertEmail:           "Por favor ingresa tu correo electrónico.",
        alertName:            "Por favor ingresa tu nombre completo.",
        alertPhone:           "Por favor ingresa tu número de teléfono.",
        loadError:            "No se pudo cargar el formulario de pago. Por favor recarga la p\u00E1gina e int\u00E9ntalo de nuevo, o cont\u00E1ctanos.",
        signedBtn:            "\u2705 Contrato de Alquiler Firmado",
        signedByNote:         "Firmado por {name}. Marca la casilla abajo para confirmar.",
        nameError:            "Por favor ingresa al menos nombre y apellido.",
        sigError:             "La firma debe coincidir con el nombre completo ingresado en el formulario de reserva.",
        calcAtCheckout:       "Calculado al pagar",
        tierRentalFmt:        "Alquiler de {label}",
        securityDepositRef:   "Dep\u00F3sito de seguridad (reembolsable)",
        securityDeposit:      "Dep\u00F3sito de seguridad",
        salesTaxFmt:          "Impuesto sobre ventas ({rate}%)",
        salesTax:             "Impuesto sobre ventas",
        dppSlingshotFmt1:     "Plan de Protecci\u00F3n de Da\u00F1os (1 d\u00EDa \u00D7 ${price}/d\u00EDa)",
        dppSlingshotFmtN:     "Plan de Protecci\u00F3n de Da\u00F1os ({days} d\u00EDas \u00D7 ${price}/d\u00EDa)",
        dppFmt:               "Plan de Protecci\u00F3n de Da\u00F1os ({detail})",
        fmtMonth1:            "1 mes \u00D7 ${price}/mes",
        fmtMonthN:            "{n} meses \u00D7 ${price}/mes",
        fmtTwoWeeks1:         "1 per\u00EDodo de 2 semanas \u00D7 ${price}",
        fmtTwoWeeksN:         "{n} per\u00EDodos de 2 semanas \u00D7 ${price}",
        fmtWeek1:             "1 semana \u00D7 ${price}/sem",
        fmtWeekN:             "{n} semanas \u00D7 ${price}/sem",
        fmtDay1:              "1 d\u00EDa \u00D7 ${price}/d\u00EDa",
        fmtDayN:              "{n} d\u00EDas \u00D7 ${price}/d\u00EDa"
      },
      agreement: {
        title: "SLY TRANSPORTATION SERVICES \u2014 CONTRATO DE ALQUILER DE VEH\u00CDCULO",
        depositHeading: "DEP\u00D3SITO DE SEGURIDAD (Reembolsable)",
        partiesHeading: "PARTES",
        partiesOwner: "<strong>Propietario:</strong> SLY Transportation Services \u2014 (213) 916-6606 \u2014 info@slytrans.com",
        partiesRenter: "<strong>Arrendatario:</strong> Nombre, direcci\u00F3n, tel\u00E9fono, correo electr\u00F3nico, n\u00FAmero de licencia de conducir y fecha de nacimiento seg\u00FAn proporcionado al momento de la reserva.",
        vehicleHeading: "INFORMACI\u00D3N DEL VEH\u00CDCULO",
        vehicleMake: "Marca",
        vehicleModel: "Modelo",
        vehicleYear: "A\u00F1o",
        vehicleVin: "VIN / Placa",
        vehicleColor: "Color",
        fuelInspection: "Nivel de Combustible al Recoger: Lleno &nbsp; Medio &nbsp; Cuarto &nbsp;&nbsp;&nbsp; Fotos de Condici\u00F3n Adjuntas: S\u00ED",
        rentalPeriodHeading: "PER\u00CDODO DE ALQUILER",
        rentalPeriodBody: "Las fechas y horas de inicio y fin del alquiler son las especificadas al momento de la reserva. El veh\u00EDculo debe ser devuelto al mismo lugar en la fecha y hora acordadas.",
        lateFeeBody: "<strong>Cargo por Mora:</strong> $50/d\u00EDa despu\u00E9s de un per\u00EDodo de gracia de 2 horas.",
        slingshotLateFeeBody: "<strong>Cargo por Mora:</strong> $100/hora despu\u00E9s de un per\u00EDodo de gracia de 30 minutos.",
        mileageFuelHeading: "POL\u00CDTICA DE MILLAJE, USO GEOGR\u00C1FICO Y RASTREO VEHICULAR",
        mileageLimitBody: "El millaje es ilimitado dentro de un \u00E1rea local designada solamente. Todo uso del veh\u00EDculo debe permanecer dentro del <strong>Condado de Los \u00C1ngeles</strong> o dentro de un <strong>radio de 50 millas de Los \u00C1ngeles</strong>, a menos que el anfitri\u00F3n lo apruebe por escrito.",
        geoAuthBody: "Los viajes fuera del \u00E1rea permitida no est\u00E1n permitidos sin autorizaci\u00F3n escrita previa. Esto incluye, entre otros, viajes a San Diego, San Francisco, Las Vegas o cualquier destino fuera del estado. Las solicitudes de viaje extendido deben presentarse con anticipaci\u00F3n y est\u00E1n sujetas a la aprobaci\u00F3n a discrecci\u00F3n exclusiva del anfitri\u00F3n.",
        geoPenaltyBody: "Cualquier uso no autorizado del veh\u00EDculo fuera del \u00E1rea geogr\u00E1fica aprobada resultar\u00E1 en un <strong>cargo de penalizaci\u00F3n de $500</strong> y puede llevar a la terminaci\u00F3n anticipada del alquiler sin reembolso, de acuerdo con las pol\u00EDticas de la plataforma.",
        gpsTrackingBody: "El veh\u00EDculo est\u00E1 equipado con un <strong>sistema de rastreo GPS</strong> por razones de seguridad y cumplimiento. Al alquilar este veh\u00EDculo, usted reconoce y consiente el monitoreo de ubicaci\u00F3n durante el per\u00EDodo de alquiler.",
        fuelHeading: "POL\u00CDTICA DE COMBUSTIBLE",
        fuelPolicyBody: "El veh\u00EDculo debe ser devuelto con el mismo nivel de combustible que al inicio del viaje. Cualquier deficiencia se cobrar\u00E1 a una tarifa de <strong>$5 por gal\u00F3n</strong>.",
        insuranceHeading: "SEGURO Y RESPONSABILIDAD",
        insuranceMustProvide: "El arrendatario debe proporcionar <strong>una de las siguientes opciones</strong> antes de la entrega del veh\u00EDculo:",
        insuranceLi1: "Seguro de auto personal v\u00E1lido que cubra veh\u00EDculos de alquiler (se requiere comprobante), <strong>O</strong>",
        insuranceLi2: "Contrataci\u00F3n del Plan de Protecci\u00F3n de Da\u00F1os de SLY Transportation Services",
        dppOptionalBody: "<strong>Plan de Protecci\u00F3n de Da\u00F1os (Opcional):</strong> B\u00E1sico &mdash; $15/d\u00EDa &bull; Est\u00E1ndar &mdash; $30/d\u00EDa &bull; Premium &mdash; $50/d\u00EDa",
        dppReduces: "Este plan reduce la responsabilidad financiera del arrendatario por da\u00F1os cubiertos al veh\u00EDculo. El l\u00EDmite de responsabilidad depende del plan seleccionado: B\u00E1sico \u2014 $2,500 \u2022 Est\u00E1ndar \u2014 $1,000 \u2022 Premium \u2014 $500 por incidente.",
        withoutPlanBody: "<strong>Sin Plan de Protecci\u00F3n:</strong> El arrendatario es totalmente responsable de todos los da\u00F1os y costos asociados, incluyendo pero no limit\u00E1ndose a:",
        withoutLi1: "Costo total de reparaci\u00F3n o reemplazo del veh\u00EDculo",
        withoutLi2: "P\u00E9rdida de uso (tiempo de inactividad del alquiler)",
        withoutLi3: "Valor disminuido",
        withoutLi4: "Honorarios administrativos, de gr\u00FAa y almacenamiento",
        withPlanBody: "<strong>Con Plan de Protecci\u00F3n:</strong> La responsabilidad m\u00E1xima del arrendatario por da\u00F1os cubiertos al veh\u00EDculo se limita seg\u00FAn el plan (B\u00E1sico: $2,500 \u2022 Est\u00E1ndar: $1,000 \u2022 Premium: $500 por incidente). Cualquier costo que exceda el l\u00EDmite est\u00E1 cubierto por el plan, siempre que se cumplan todos los t\u00E9rminos de este contrato.",
        exclusionsBody: "<strong>Exclusiones (Plan de Protecci\u00F3n Anulado Si):</strong>",
        exclusionLi1: "El conductor est\u00E1 bajo la influencia de drogas o alcohol",
        exclusionLi2: "Un conductor no autorizado opera el veh\u00EDculo",
        exclusionLi3: "Uso imprudente, ilegal o negligente",
        exclusionLi4: "Uso fuera de carretera o prohibido",
        exclusionLi5: "No reportar da\u00F1os dentro de 24 horas",
        exclusionLi6: "Violaci\u00F3n de los t\u00E9rminos del contrato de alquiler",
        thirdPartyBody: "<strong>Responsabilidad ante Terceros:</strong> El arrendatario es el \u00FAnico responsable de cualquier reclamaci\u00F3n de terceros, incluyendo lesiones corporales, da\u00F1os a la propiedad o muerte. SLY Transportation Services no es responsable por la negligencia del arrendatario. El arrendatario acepta indemnizar y eximir de responsabilidad a SLY Transportation Services de cualquier reclamaci\u00F3n, p\u00E9rdida o gasto derivado del uso del veh\u00EDculo.",
        useRestrictionsHeading: "RESTRICCIONES DE USO",
        useRestrictionsIntro: "El arrendatario acepta todas las siguientes restricciones:",
        useRestrictionsRow1: "No fumar &nbsp; No mascotas &nbsp; No uso fuera de carretera &nbsp; No subarrendar",
        useRestrictionsRow2: "Solo conductores aprobados &nbsp; No carreras ni remolque &nbsp; No transporte comercial de mercanc\u00EDas",
        slingshotSpeedHeading: "POL\u00CDTICA DE VELOCIDAD SLINGSHOT",
        slingshotSpeedBody: "<strong>L\u00EDmite de Velocidad:</strong> El l\u00EDmite de velocidad publicado es de 65 mph. Los arrendatarios no pueden superar <strong>75 mph</strong> bajo ninguna circunstancia. Superar 75 mph en cualquier momento constituye una violaci\u00F3n de este contrato.",
        slingshotStrikePolicy: "<strong>Pol\u00EDtica de Infracciones:</strong> Despu\u00E9s de dos (2) infracciones de velocidad o del contrato (\"strikes\"), el dep\u00F3sito de seguridad del arrendatario se vuelve <strong>no reembolsable</strong>.",
        conditionHeading: "INSPECCI\u00D3N DE CONDICI\u00D3N",
        conditionBody: "El veh\u00EDculo es inspeccionado y aceptado tal como est\u00E1 al momento de la recogida. Se toman fotos de la condici\u00F3n al recoger. El arrendatario debe reportar cualquier da\u00F1o preexistente dentro de las 24 horas posteriores a la recogida.",
        terminationHeading: "TERMINACI\u00D3N",
        terminationBody: "SLY Transportation Services puede terminar este contrato de inmediato por incumplimiento de t\u00E9rminos, cargos impagos, uso ilegal o violaciones de seguridad. El arrendatario es responsable de todos los costos de recuperaci\u00F3n del veh\u00EDculo.",
        paymentTermsHeading: "T\u00C9RMINOS DE PAGO",
        paymentTermsBody: "Todos los cargos se deben al momento de la recogida. Los pagos atrasados acumulan inter\u00E9s del 1.5% mensual. Cargo por cheque devuelto (NSF): $35.",
        noRefundBody: "\u26A0 <strong>Pol\u00EDtica de No Reembolso:</strong> Todos los pagos son finales una vez confirmada la reserva. Las cancelaciones o ausencias despu\u00E9s de la reserva no son elegibles para reembolso. Los reembolsos solo se emiten si SLY Transportation cancela o no puede cumplir con el alquiler.",
        chargebackHeading: "AUTORIZACI\u00D3N DE PAGO Y POL\u00CDTICA DE CONTRACARGOS",
        chargebackIntro: "Al firmar este contrato, el arrendatario autoriza expresamente a SLY Transportation Services a cargar el m\u00E9todo de pago registrado por todos los montos adeudados bajo este contrato, incluyendo pero no limit\u00E1ndose a:",
        chargebackLi1: "Cargos de alquiler y extensiones",
        chargebackLi2: "Dep\u00F3sito de seguridad y deducciones aplicables",
        chargebackLi3: "Costos de da\u00F1os, reparaci\u00F3n o reemplazo del veh\u00EDculo",
        chargebackLi4: "P\u00E9rdida de uso y valor disminuido",
        chargebackLi5: "Cargos por combustible, limpieza, fumar o desgaste excesivo",
        chargebackLi6: "Gr\u00FAa, almacenamiento, multas, peajes y honorarios administrativos",
        chargebackAfter: "El arrendatario acepta que estos cargos pueden procesarse despu\u00E9s del per\u00EDodo de alquiler si se identifican costos adicionales en la inspecci\u00F3n o descubrimiento posterior.",
        chargebackAcknowledge: "El arrendatario reconoce que todos los cargos son v\u00E1lidos, acordados y autorizados bajo este contrato. El arrendatario acepta no disputar, revertir o iniciar un contracargo por cualquier cargo leg\u00EDtimo incurrido de acuerdo con este contrato.",
        chargebackDisputeBody: "<strong>En caso de una disputa de pago o contracargo, el arrendatario acepta que:</strong>",
        chargebackDisputeLi1: "Este contrato firmado sirve como prueba vinculante de autorizaci\u00F3n",
        chargebackDisputeLi2: "SLY Transportation Services puede presentar este contrato, junto con registros de alquiler, fotos, informes de inspecci\u00F3n y registros de comunicaci\u00F3n, como evidencia al procesador de pagos",
        chargebackDisputeLi3: "El arrendatario sigue siendo financieramente responsable de todos los cargos, incluidas las tarifas resultantes de la disputa",
        chargebackChargeback: "Si se inicia un contracargo sin causa v\u00E1lida, SLY Transportation Services se reserva el derecho de recurrir a cobro, acciones legales y recuperaci\u00F3n de todos los costos asociados, incluidos honorarios razonables de abogados donde lo permita la ley.",
        governingLawHeading: "LEY APLICABLE",
        governingLawBody: "Este contrato se rige por las leyes del Estado de California. Las disputas se resolver\u00E1n en los tribunales del Condado de Los \u00C1ngeles. Al firmar, el arrendatario reconoce que ha le\u00EDdo, comprendido y aceptado todos los t\u00E9rminos anteriores."
      },
      contact: {
        heading:  "Cont\u00E1ctanos",
        subtitle: "\u00BFTienes alguna pregunta o necesitas ayuda? Env\u00EDanos un mensaje y te responderemos pronto.",
        labelName:    "Tu Nombre",
        labelEmail:   "Tu Correo Electr\u00F3nico",
        labelPhone:   "Tel\u00E9fono (opcional)",
        labelMessage: "Tu Mensaje",
        placeholderName:    "Nombre y apellido",
        placeholderEmail:   "tu@ejemplo.com",
        placeholderPhone:   "(213) 555-0100",
        placeholderMessage: "\u00BFC\u00F3mo podemos ayudarte?",
        sendBtn:  "Enviar Mensaje",
        otpLabel: "C\u00F3digo de Verificaci\u00F3n",
        otpPh:    "Ingresa el c\u00F3digo de 6 d\u00EDgitos",
        sendOtp:  "Enviar C\u00F3digo",
        resend:   "Reenviar",
        emailVerified: "\u2713 Correo verificado",
        otpHint:      "Revisa tu bandeja de entrada para un c\u00F3digo de 6 d\u00EDgitos (v\u00E1lido 10 min).",
        otpSent:      "\u00A1C\u00F3digo de verificaci\u00F3n enviado! Revisa tu bandeja de entrada.",
        otpSentError: "No se pudo enviar el correo de verificaci\u00F3n. Por favor int\u00E9ntalo de nuevo.",
        networkError: "Error de red. Por favor verifica tu conexi\u00F3n e int\u00E9ntalo de nuevo.",
        sendCodeBtn:  "Enviar C\u00F3digo",
        sentDone:     "Enviado \u2713",
        sendingCode:  "Enviando\u2026",
        resendFmt:    "Reenviar ({secs}s)",
        enterEmailFirst:   "Por favor ingresa tu correo electr\u00F3nico primero.",
        enterValidEmail:   "Por favor ingresa una direcci\u00F3n de correo electr\u00F3nico v\u00E1lida.",
        fillAllFields:     "Por favor completa todos los campos requeridos.",
        verifyEmailFirst:  "Por favor verifica tu correo electr\u00F3nico antes de enviar.",
        enterOtpCode:      "Por favor ingresa el c\u00F3digo de verificaci\u00F3n enviado a tu correo.",
        sending:           "Enviando\u2026",
        generalError:      "Algo sali\u00F3 mal. Por favor int\u00E9ntalo de nuevo o ll\u00E1manos al (213) 916-6606.",
        networkErrorFull:  "Error de red. Por favor verifica tu conexi\u00F3n o ll\u00E1manos al (213) 916-6606."
      },
      success: {
        title:      "\u2705 \u00A1Pago Exitoso!",
        body:       "\u00A1Gracias por reservar con Sly Transportation Services LLC! Tu auto est\u00E1 reservado. Nos pondremos en contacto contigo pronto para confirmar los detalles de tu alquiler.",
        sending:    "Enviando confirmaci\u00F3n\u2026",
        homeBtn:    "Volver a la Reserva",
        failTitle:  "\u274C Pago Fallido",
        failBody:   "Tu pago no fue completado. No se realiz\u00F3 ning\u00FAn cargo. Por favor intenta reservar de nuevo o cont\u00E1ctanos si necesitas ayuda.",
        pendingTitle: "\u23F3 Pago en Proceso",
        pendingBody:  "Tu pago est\u00E1 siendo procesado. Te enviaremos un correo una vez que sea confirmado. Por favor no vuelvas a enviar.",
        emailError: "No pudimos enviar tu correo de confirmaci\u00F3n autom\u00E1ticamente. Por favor cont\u00E1ctanos en slyservices@supports-info.com para confirmar tu reserva.",
        tryAgain:  "Intentar Reservar de Nuevo",
        verifying: "Verificando pago\u2026"
      },
      cancel: {
        title:   "\u274C Pago Cancelado",
        body:    "Tu pago no fue completado. No se realiz\u00F3 ning\u00FAn cargo. \u00A1Puedes intentarlo de nuevo en cualquier momento!",
        homeBtn: "Volver al Inicio",
        tryAgain: "Intentar Reservar de Nuevo"
      },
      thankyou: {
        title:          "\uD83C\uDF89 \u00A1Gracias!",
        sub:            "\u00A1Tu solicitud ha sido recibida!",
        detail:         "Nuestro equipo en Sly Transportation Services LLC revisar\u00E1 tu informaci\u00F3n y se comunicar\u00E1 contigo pronto para completar tu aprobaci\u00F3n.",
        download:       "📄 Descargar PDF",
        fillAgain:      "🔄 Completar de Nuevo",
        questions:      "\u00BFPreguntas? Ll\u00E1manos:",
        browseCars:     "\uD83D\uDE97 Ver y Reservar un Auto",
        backHome:       "\uD83C\uDFE0 Volver al Inicio",
        approvedTitle:  "\uD83C\uDF89 \u00A1Est\u00E1s Aprobado!",
        approvedSub:    "Felicitaciones \u2014 \u00A1tu solicitud ha sido aceptada!",
        approvedDetail: "Ya puedes ver y reservar un veh\u00EDculo con <strong>Sly Transportation Services LLC</strong>. Revisa tu correo para la confirmaci\u00F3n oficial de aprobaci\u00F3n y los pr\u00F3ximos pasos.",
        reviewTitle:    "\u23F3 \u00A1Solicitud Recibida!",
        reviewSub:      "Estamos revisando tu informaci\u00F3n ahora.",
        reviewDetail:   "Nuestro equipo en <strong>Sly Transportation Services LLC</strong> revisar\u00E1 tu solicitud y se comunicar\u00E1 contigo en <strong>24 horas</strong>. Revisa tu correo y tel\u00E9fono para actualizaciones.",
        declinedTitle:  "Actualizaci\u00F3n de Solicitud",
        declinedSub:    "No pudimos aprobar tu solicitud en este momento.",
        declinedDetail: "Tu solicitud no cumple actualmente con nuestros requisitos de alquiler. Se ha enviado una confirmaci\u00F3n a tu correo. Si crees que esto es un error o tienes preguntas, ll\u00E1manos al <strong>(213) 916-6606</strong>."
      },
      chatbot: {
        headerTitle:  "\uD83D\uDE97 Asistente de Sly Transportation Services LLC",
        placeholder:  "Haz una pregunta\u2026",
        sendBtn:      "Enviar",
        closeBtn:     "\u2715",
        welcome:      "\u00A1Hola! \uD83D\uDC4B \u00BFQuieres alquilar un auto para DoorDash, Uber Eats u otras aplicaciones de entrega?\n\nNuestros autos son <strong>$350/semana con millaje ilimitado</strong>. Puedo ayudarte a obtener aprobaci\u00F3n r\u00E1pidamente.\n\nPr\u00E9guntame lo que quieras \u2014 precios, requisitos, ganancias \u2014 o haz clic abajo para solicitar.\n\n<a href=\"index.html\" id=\"chatApplyLink\">\uD83D\uDC49 Solicitar y obtener aprobaci\u00F3n ahora</a>",
        fallback:     "No estoy seguro de eso \uD83E\uDD14\n\nIntenta preguntar sobre:\n\u2022 Precios\n\u2022 Autos disponibles\n\u2022 C\u00F3mo reservar\n\u2022 Aplicaciones de entrega\n\u2022 Informaci\u00F3n de contacto\n\nO env\u00EDanos un correo a slyservices@supports-info.com"
      },
      footer: {
        copy: "\u00A9 2026 Sly Transportation Services LLC. Todos los derechos reservados.",
        privacyPolicy: "Pol\u00EDtica de Privacidad"
      }
    }
  };

  // ── Helpers ───────────────────────────────────────────────────────────────
  function getLang() {
    return localStorage.getItem("slyLang") || "en";
  }

  function getVal(obj, keyPath) {
    return keyPath.split(".").reduce(function (o, k) { return o && o[k]; }, obj);
  }

  function t(key) {
    var lang = getLang();
    var val = getVal(TRANSLATIONS[lang], key);
    if (val === undefined) val = getVal(TRANSLATIONS["en"], key);
    return (val !== undefined) ? val : key;
  }

  // ── Apply translations to DOM ─────────────────────────────────────────────
  function applyTranslations() {
    // textContent replacements
    document.querySelectorAll("[data-i18n]").forEach(function (el) {
      var key = el.getAttribute("data-i18n");
      var val = t(key);
      if (val !== key) el.textContent = val;
    });
    // placeholder replacements
    document.querySelectorAll("[data-i18n-placeholder]").forEach(function (el) {
      var key = el.getAttribute("data-i18n-placeholder");
      var val = t(key);
      if (val !== key) el.setAttribute("placeholder", val);
    });
    // aria-label replacements
    document.querySelectorAll("[data-i18n-aria]").forEach(function (el) {
      var key = el.getAttribute("data-i18n-aria");
      var val = t(key);
      if (val !== key) el.setAttribute("aria-label", val);
    });
    // innerHTML replacements (trusted static content only)
    document.querySelectorAll("[data-i18n-html]").forEach(function (el) {
      var key = el.getAttribute("data-i18n-html");
      var val = t(key);
      if (val !== key) el.innerHTML = val;
    });
    // Update <html lang> attribute
    document.documentElement.lang = getLang() === "es" ? "es" : "en";
    // Update switcher button states
    document.querySelectorAll(".lang-btn").forEach(function (btn) {
      btn.classList.toggle("active", btn.getAttribute("data-lang") === getLang());
    });
  }

  // ── Language switcher ─────────────────────────────────────────────────────
  function buildSwitcher() {
    var header = document.querySelector(".site-header");
    if (!header) return;
    if (document.getElementById("langSwitcher")) return; // already built
    var div = document.createElement("div");
    div.id = "langSwitcher";
    div.className = "lang-switcher";
    div.setAttribute("aria-label", "Language / Idioma");
    div.innerHTML =
      '<button class="lang-btn" data-lang="en" title="English" aria-label="English">' +
        '<span class="lang-flag">\uD83C\uDDFA\uD83C\uDDF8</span><span class="lang-label">EN</span>' +
      '</button>' +
      '<button class="lang-btn" data-lang="es" title="Espa\u00F1ol" aria-label="Espa\u00F1ol">' +
        '<span class="lang-flag">\uD83C\uDDF2\uD83C\uDDFD</span><span class="lang-label">ES</span>' +
      '</button>';
    header.appendChild(div);
    div.querySelectorAll(".lang-btn").forEach(function (btn) {
      btn.addEventListener("click", function () {
        localStorage.setItem("slyLang", btn.getAttribute("data-lang"));
        window.currentLang = btn.getAttribute("data-lang");
        applyTranslations();
        // Notify chatbot if already built
        if (typeof window.updateChatbotLang === "function") {
          window.updateChatbotLang(getLang());
        }
      });
    });
  }

  // ── Init ──────────────────────────────────────────────────────────────────
  function init() {
    window.currentLang = getLang();
    buildSwitcher();
    applyTranslations();
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }

  // ── Public API (used by chatbot.js and car.js) ────────────────────────────
  window.slyI18n = {
    t:    t,
    getLang: getLang,
    applyTranslations: applyTranslations,
    TRANSLATIONS: TRANSLATIONS
  };
}());
